[INFO] [1740092466.880078144] [alarme_service]: Service BP alarme : OK
[INFO] [1740092491.925297168] [alarme_service]: ALARME ON
[INFO] [1740092497.736394308] [alarme_service]: ALARME OFF
Traceback (most recent call last):
  File "/home/thogms/ros2_ws/install/projet_pkg/lib/projet_pkg/service_bp", line 33, in <module>
    sys.exit(load_entry_point('projet-pkg==0.0.0', 'console_scripts', 'service_bp')())
  File "/home/thogms/ros2_ws/install/projet_pkg/lib/python3.10/site-packages/projet_pkg/service_bp.py", line 33, in main
    rclpy.spin(alarme_service)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 226, in spin
    executor.spin_once()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 739, in spin_once
    self._spin_once_impl(timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 728, in _spin_once_impl
    handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 711, in wait_for_ready_callbacks
    return next(self._cb_iter)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 612, in _wait_for_ready_callbacks
    raise ExternalShutdownException()
rclpy.executors.ExternalShutdownException
[ros2run]: Process exited with failure 1
